name: Deploy app

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: connect to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SERVER_PORT }}
                  script: |
                    set -e #detects errors and stops execution

                    # Cargar entorno de nvm y usar Node.js 20
                    export NVM_DIR="$HOME/.nvm"
                    source "$NVM_DIR/nvm.sh"
                    nvm use 20.14.0

                    cd /home/ubuntu/pm2-project
                    echo "Pulling latest changes..."
                    git pull
                    echo "running deploy.sh..."
                    bash deploy.sh
                    echo "deploy successful!"
              continue-on-error: false   